# policy
set(CMAKE_POLICY_DEFAULT_CMP0069 NEW)
set(CMAKE_POLICY_DEFAULT_CMP0111 NEW)


# post hook
set(_ysm_project_include "${CMAKE_CURRENT_LIST_DIR}/post-setup.cmake")
if(DEFINED CMAKE_PROJECT_INCLUDE AND NOT CMAKE_PROJECT_INCLUDE STREQUAL "")
    set(CMAKE_PROJECT_INCLUDE "${_ysm_project_include};${CMAKE_PROJECT_INCLUDE}" CACHE STRING "" FORCE)
else()
    set(CMAKE_PROJECT_INCLUDE "${_ysm_project_include}" CACHE STRING "" FORCE)
endif()


# flag util
function(_ysm_split_custom_options _out_common_options _out_llvm_options)
    set(_common_options)
    set(_llvm_options)
    set(_current_options _common_options)

    foreach(_opt IN LISTS ARGN)
        if(_opt STREQUAL "LLVM")
            if("${_current_options}" STREQUAL "_llvm_options")
                message(FATAL_ERROR "LLVM option separator may only appear once.")
            endif()
            set(_current_options _llvm_options)
        else()
            list(APPEND ${_current_options} "${_opt}")
        endif()
    endforeach()

    set(${_out_common_options} ${_common_options} PARENT_SCOPE)
    set(${_out_llvm_options} ${_llvm_options} PARENT_SCOPE)
endfunction()

function(add_c_compile_options)
    _ysm_split_custom_options(_common_options _llvm_options ${ARGN})
    foreach(_opt IN LISTS _common_options)
        add_compile_options("$<$<OR:$<COMPILE_LANGUAGE:C>,$<COMPILE_LANGUAGE:CXX>>:${_opt}>")
    endforeach()
    if (CMAKE_C_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if(CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC" OR CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            foreach(_opt IN LISTS _llvm_options)
                add_compile_options("$<$<OR:$<COMPILE_LANGUAGE:C>,$<COMPILE_LANGUAGE:CXX>>:/clang:${_opt}>")
            endforeach()
        else ()
            foreach(_opt IN LISTS _llvm_options)
                add_compile_options("$<$<OR:$<COMPILE_LANGUAGE:C>,$<COMPILE_LANGUAGE:CXX>>:${_opt}>")
            endforeach()
        endif ()
    endif ()
endfunction()

function(add_cxx_compile_options)
    _ysm_split_custom_options(_common_options _llvm_options ${ARGN})
    foreach(_opt IN LISTS _common_options)
        add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:${_opt}>")
    endforeach()
    if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
            foreach(_opt IN LISTS _llvm_options)
                add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:/clang:${_opt}>")
            endforeach()
        else ()
            foreach(_opt IN LISTS _llvm_options)
                add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:${_opt}>")
            endforeach()
        endif ()
    endif ()
endfunction()

function(add_custom_link_options)
    _ysm_split_custom_options(_common_options _llvm_options ${ARGN})
    if(_common_options)
        add_link_options(${_common_options})
    endif()
    if (_llvm_options AND CMAKE_LINKER_TYPE STREQUAL "LLD")
        add_link_options(${_llvm_options})
    endif ()
endfunction()

