if (NOT DEFINED TARGET_OS)
    string(TOUPPER "${CMAKE_SYSTEM_NAME}" _UPPER_OS)
    if (_UPPER_OS STREQUAL "WINDOWS")
        set(TARGET_OS "WINDOWS")
    elseif (_UPPER_OS STREQUAL "LINUX" AND NOT ANDROID)
        set(TARGET_OS "LINUX")
    elseif (_UPPER_OS STREQUAL "ANDROID" OR ANDROID)
        set(TARGET_OS "ANDROID")
    elseif (_UPPER_OS STREQUAL "DARWIN")
        set(TARGET_OS "MACOS")
    else ()
        set(TARGET_OS _UPPER_OS)
        message(WARNING "Target os '${CMAKE_SYSTEM_NAME}' has not been verified by this project.")
    endif ()
    unset(_UPPER_OS)
endif ()

if (NOT DEFINED TARGET_ARCH)
    string(TOUPPER "${CMAKE_SYSTEM_PROCESSOR}" _UPPER_ARCH)
    if (_UPPER_ARCH MATCHES "AMD64|X86_64")
        set(TARGET_ARCH "X64")
    elseif (_UPPER_ARCH MATCHES "AARCH64|ARM64|ARMV8")
        set(TARGET_ARCH "ARM64")
    else ()
        set(TARGET_ARCH _UPPER_ARCH)
        message(WARNING "Target arch '${CMAKE_SYSTEM_PROCESSOR}' has not been verified by this project.")
    endif ()
    unset(_UPPER_ARCH)
endif ()

set(YSM_${TARGET_OS} ON)
set(YSM_${TARGET_ARCH} ON)
string(TOLOWER "${TARGET_OS}-${TARGET_ARCH}" YSM_TARGET)
add_compile_definitions(YSM_${TARGET_OS}=1 YSM_${TARGET_ARCH}=1 "YSM_TARGET=\"${YSM_TARGET}\"")

set(ysm_target_settings "${CMAKE_CURRENT_LIST_DIR}/targets/${YSM_TARGET}.cmake")
if (EXISTS ${ysm_target_settings})
    get_property(ysm_in_try_compile GLOBAL PROPERTY IN_TRY_COMPILE)
    include(${ysm_target_settings})
    unset(ysm_in_try_compile)
else ()
    message(WARNING "Target '${YSM_TARGET}' has not been verified by this project.")
endif ()
unset(ysm_target_settings)
