namespace ysm.bake.fb;

table CubeAttr {
    quad_count:ubyte;
    quad_count_after_culling:ubyte;
    uv:[float];
    mid_uv:[float];
}

table CubeGroup {
    pos:[float];
    center:[float];
    normal:[float];
    plane_d:[float];
    winding_sign:[float];
    tangent:[float];
    vertex_index:[uint];
    cube_attr:[CubeAttr];
    cube_count:uint;
    bone_index:uint;
    vertex_offset:uint;
}

struct CubeGroupInfo {
    cube_count:uint;
    quad_count:uint;
    quad_count_after_culling:uint;
}

table BonePartitionInfo {
    cube_indices:[uint];
    full_vertex_count:uint;
    culling_vertex_count:uint;
    cube_count:uint;
    cube_group_info:[CubeGroupInfo];
}

table BoneInfo {
    cutout:BonePartitionInfo;
    cutout_no_culling:BonePartitionInfo;
    translucent:BonePartitionInfo;
    translucent_culling:BonePartitionInfo;
    solid:bool;
    pivot:[float];
    parent_index:uint = 4294967295;
    subtree_end:uint;
    depth:uint;
}

table CubeData {
    cutout:[CubeGroup];
    cutout_no_culling:[CubeGroup];
    translucent:[CubeGroup];
    translucent_culling:[CubeGroup];
}

table BakedModel {
    bones:[BoneInfo];
    sorted_bone_indices:[ushort];
    cubes:CubeData;
    gui_no_shadow:bool = false;
    has_pbr:bool = false;
}

root_type BakedModel;
