// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BAKEDMODEL_YSM_BAKE_FB_H_
#define FLATBUFFERS_GENERATED_BAKEDMODEL_YSM_BAKE_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ysm {
namespace bake {
namespace fb {

struct CubeAttr;
struct CubeAttrBuilder;

struct CubeGroup;
struct CubeGroupBuilder;

struct CubeGroupInfo;

struct BonePartitionInfo;
struct BonePartitionInfoBuilder;

struct BoneInfo;
struct BoneInfoBuilder;

struct CubeData;
struct CubeDataBuilder;

struct BakedModel;
struct BakedModelBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) CubeGroupInfo FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t cube_count_;
  uint32_t quad_count_;
  uint32_t quad_count_after_culling_;

 public:
  struct Traits;
  CubeGroupInfo()
      : cube_count_(0),
        quad_count_(0),
        quad_count_after_culling_(0) {
  }
  CubeGroupInfo(uint32_t _cube_count, uint32_t _quad_count, uint32_t _quad_count_after_culling)
      : cube_count_(::flatbuffers::EndianScalar(_cube_count)),
        quad_count_(::flatbuffers::EndianScalar(_quad_count)),
        quad_count_after_culling_(::flatbuffers::EndianScalar(_quad_count_after_culling)) {
  }
  uint32_t cube_count() const {
    return ::flatbuffers::EndianScalar(cube_count_);
  }
  uint32_t quad_count() const {
    return ::flatbuffers::EndianScalar(quad_count_);
  }
  uint32_t quad_count_after_culling() const {
    return ::flatbuffers::EndianScalar(quad_count_after_culling_);
  }
};
FLATBUFFERS_STRUCT_END(CubeGroupInfo, 12);

struct CubeGroupInfo::Traits {
  using type = CubeGroupInfo;
};

struct CubeAttr FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CubeAttrBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUAD_COUNT = 4,
    VT_QUAD_COUNT_AFTER_CULLING = 6,
    VT_UV = 8,
    VT_MID_UV = 10
  };
  uint8_t quad_count() const {
    return GetField<uint8_t>(VT_QUAD_COUNT, 0);
  }
  uint8_t quad_count_after_culling() const {
    return GetField<uint8_t>(VT_QUAD_COUNT_AFTER_CULLING, 0);
  }
  const ::flatbuffers::Vector<float> *uv() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_UV);
  }
  const ::flatbuffers::Vector<float> *mid_uv() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_MID_UV);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_QUAD_COUNT, 1) &&
           VerifyField<uint8_t>(verifier, VT_QUAD_COUNT_AFTER_CULLING, 1) &&
           VerifyOffset(verifier, VT_UV) &&
           verifier.VerifyVector(uv()) &&
           VerifyOffset(verifier, VT_MID_UV) &&
           verifier.VerifyVector(mid_uv()) &&
           verifier.EndTable();
  }
};

struct CubeAttrBuilder {
  typedef CubeAttr Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_quad_count(uint8_t quad_count) {
    fbb_.AddElement<uint8_t>(CubeAttr::VT_QUAD_COUNT, quad_count, 0);
  }
  void add_quad_count_after_culling(uint8_t quad_count_after_culling) {
    fbb_.AddElement<uint8_t>(CubeAttr::VT_QUAD_COUNT_AFTER_CULLING, quad_count_after_culling, 0);
  }
  void add_uv(::flatbuffers::Offset<::flatbuffers::Vector<float>> uv) {
    fbb_.AddOffset(CubeAttr::VT_UV, uv);
  }
  void add_mid_uv(::flatbuffers::Offset<::flatbuffers::Vector<float>> mid_uv) {
    fbb_.AddOffset(CubeAttr::VT_MID_UV, mid_uv);
  }
  explicit CubeAttrBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CubeAttr> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CubeAttr>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CubeAttr> CreateCubeAttr(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t quad_count = 0,
    uint8_t quad_count_after_culling = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> uv = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> mid_uv = 0) {
  CubeAttrBuilder builder_(_fbb);
  builder_.add_mid_uv(mid_uv);
  builder_.add_uv(uv);
  builder_.add_quad_count_after_culling(quad_count_after_culling);
  builder_.add_quad_count(quad_count);
  return builder_.Finish();
}

struct CubeAttr::Traits {
  using type = CubeAttr;
  static auto constexpr Create = CreateCubeAttr;
};

inline ::flatbuffers::Offset<CubeAttr> CreateCubeAttrDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t quad_count = 0,
    uint8_t quad_count_after_culling = 0,
    const std::vector<float> *uv = nullptr,
    const std::vector<float> *mid_uv = nullptr) {
  auto uv__ = uv ? _fbb.CreateVector<float>(*uv) : 0;
  auto mid_uv__ = mid_uv ? _fbb.CreateVector<float>(*mid_uv) : 0;
  return ysm::bake::fb::CreateCubeAttr(
      _fbb,
      quad_count,
      quad_count_after_culling,
      uv__,
      mid_uv__);
}

struct CubeGroup FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CubeGroupBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POS = 4,
    VT_CENTER = 6,
    VT_NORMAL = 8,
    VT_PLANE_D = 10,
    VT_WINDING_SIGN = 12,
    VT_TANGENT = 14,
    VT_VERTEX_INDEX = 16,
    VT_CUBE_ATTR = 18,
    VT_CUBE_COUNT = 20,
    VT_BONE_INDEX = 22,
    VT_VERTEX_OFFSET = 24
  };
  const ::flatbuffers::Vector<float> *pos() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_POS);
  }
  const ::flatbuffers::Vector<float> *center() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_CENTER);
  }
  const ::flatbuffers::Vector<float> *normal() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_NORMAL);
  }
  const ::flatbuffers::Vector<float> *plane_d() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_PLANE_D);
  }
  const ::flatbuffers::Vector<float> *winding_sign() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_WINDING_SIGN);
  }
  const ::flatbuffers::Vector<float> *tangent() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TANGENT);
  }
  const ::flatbuffers::Vector<uint32_t> *vertex_index() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_VERTEX_INDEX);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeAttr>> *cube_attr() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeAttr>> *>(VT_CUBE_ATTR);
  }
  uint32_t cube_count() const {
    return GetField<uint32_t>(VT_CUBE_COUNT, 0);
  }
  uint32_t bone_index() const {
    return GetField<uint32_t>(VT_BONE_INDEX, 0);
  }
  uint32_t vertex_offset() const {
    return GetField<uint32_t>(VT_VERTEX_OFFSET, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POS) &&
           verifier.VerifyVector(pos()) &&
           VerifyOffset(verifier, VT_CENTER) &&
           verifier.VerifyVector(center()) &&
           VerifyOffset(verifier, VT_NORMAL) &&
           verifier.VerifyVector(normal()) &&
           VerifyOffset(verifier, VT_PLANE_D) &&
           verifier.VerifyVector(plane_d()) &&
           VerifyOffset(verifier, VT_WINDING_SIGN) &&
           verifier.VerifyVector(winding_sign()) &&
           VerifyOffset(verifier, VT_TANGENT) &&
           verifier.VerifyVector(tangent()) &&
           VerifyOffset(verifier, VT_VERTEX_INDEX) &&
           verifier.VerifyVector(vertex_index()) &&
           VerifyOffset(verifier, VT_CUBE_ATTR) &&
           verifier.VerifyVector(cube_attr()) &&
           verifier.VerifyVectorOfTables(cube_attr()) &&
           VerifyField<uint32_t>(verifier, VT_CUBE_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_BONE_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_VERTEX_OFFSET, 4) &&
           verifier.EndTable();
  }
};

struct CubeGroupBuilder {
  typedef CubeGroup Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pos(::flatbuffers::Offset<::flatbuffers::Vector<float>> pos) {
    fbb_.AddOffset(CubeGroup::VT_POS, pos);
  }
  void add_center(::flatbuffers::Offset<::flatbuffers::Vector<float>> center) {
    fbb_.AddOffset(CubeGroup::VT_CENTER, center);
  }
  void add_normal(::flatbuffers::Offset<::flatbuffers::Vector<float>> normal) {
    fbb_.AddOffset(CubeGroup::VT_NORMAL, normal);
  }
  void add_plane_d(::flatbuffers::Offset<::flatbuffers::Vector<float>> plane_d) {
    fbb_.AddOffset(CubeGroup::VT_PLANE_D, plane_d);
  }
  void add_winding_sign(::flatbuffers::Offset<::flatbuffers::Vector<float>> winding_sign) {
    fbb_.AddOffset(CubeGroup::VT_WINDING_SIGN, winding_sign);
  }
  void add_tangent(::flatbuffers::Offset<::flatbuffers::Vector<float>> tangent) {
    fbb_.AddOffset(CubeGroup::VT_TANGENT, tangent);
  }
  void add_vertex_index(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> vertex_index) {
    fbb_.AddOffset(CubeGroup::VT_VERTEX_INDEX, vertex_index);
  }
  void add_cube_attr(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeAttr>>> cube_attr) {
    fbb_.AddOffset(CubeGroup::VT_CUBE_ATTR, cube_attr);
  }
  void add_cube_count(uint32_t cube_count) {
    fbb_.AddElement<uint32_t>(CubeGroup::VT_CUBE_COUNT, cube_count, 0);
  }
  void add_bone_index(uint32_t bone_index) {
    fbb_.AddElement<uint32_t>(CubeGroup::VT_BONE_INDEX, bone_index, 0);
  }
  void add_vertex_offset(uint32_t vertex_offset) {
    fbb_.AddElement<uint32_t>(CubeGroup::VT_VERTEX_OFFSET, vertex_offset, 0);
  }
  explicit CubeGroupBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CubeGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CubeGroup>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CubeGroup> CreateCubeGroup(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> pos = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> center = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> normal = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> plane_d = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> winding_sign = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> tangent = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> vertex_index = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeAttr>>> cube_attr = 0,
    uint32_t cube_count = 0,
    uint32_t bone_index = 0,
    uint32_t vertex_offset = 0) {
  CubeGroupBuilder builder_(_fbb);
  builder_.add_vertex_offset(vertex_offset);
  builder_.add_bone_index(bone_index);
  builder_.add_cube_count(cube_count);
  builder_.add_cube_attr(cube_attr);
  builder_.add_vertex_index(vertex_index);
  builder_.add_tangent(tangent);
  builder_.add_winding_sign(winding_sign);
  builder_.add_plane_d(plane_d);
  builder_.add_normal(normal);
  builder_.add_center(center);
  builder_.add_pos(pos);
  return builder_.Finish();
}

struct CubeGroup::Traits {
  using type = CubeGroup;
  static auto constexpr Create = CreateCubeGroup;
};

inline ::flatbuffers::Offset<CubeGroup> CreateCubeGroupDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *pos = nullptr,
    const std::vector<float> *center = nullptr,
    const std::vector<float> *normal = nullptr,
    const std::vector<float> *plane_d = nullptr,
    const std::vector<float> *winding_sign = nullptr,
    const std::vector<float> *tangent = nullptr,
    const std::vector<uint32_t> *vertex_index = nullptr,
    const std::vector<::flatbuffers::Offset<ysm::bake::fb::CubeAttr>> *cube_attr = nullptr,
    uint32_t cube_count = 0,
    uint32_t bone_index = 0,
    uint32_t vertex_offset = 0) {
  auto pos__ = pos ? _fbb.CreateVector<float>(*pos) : 0;
  auto center__ = center ? _fbb.CreateVector<float>(*center) : 0;
  auto normal__ = normal ? _fbb.CreateVector<float>(*normal) : 0;
  auto plane_d__ = plane_d ? _fbb.CreateVector<float>(*plane_d) : 0;
  auto winding_sign__ = winding_sign ? _fbb.CreateVector<float>(*winding_sign) : 0;
  auto tangent__ = tangent ? _fbb.CreateVector<float>(*tangent) : 0;
  auto vertex_index__ = vertex_index ? _fbb.CreateVector<uint32_t>(*vertex_index) : 0;
  auto cube_attr__ = cube_attr ? _fbb.CreateVector<::flatbuffers::Offset<ysm::bake::fb::CubeAttr>>(*cube_attr) : 0;
  return ysm::bake::fb::CreateCubeGroup(
      _fbb,
      pos__,
      center__,
      normal__,
      plane_d__,
      winding_sign__,
      tangent__,
      vertex_index__,
      cube_attr__,
      cube_count,
      bone_index,
      vertex_offset);
}

struct BonePartitionInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BonePartitionInfoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CUBE_INDICES = 4,
    VT_FULL_VERTEX_COUNT = 6,
    VT_CULLING_VERTEX_COUNT = 8,
    VT_CUBE_COUNT = 10,
    VT_CUBE_GROUP_INFO = 12
  };
  const ::flatbuffers::Vector<uint32_t> *cube_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_CUBE_INDICES);
  }
  uint32_t full_vertex_count() const {
    return GetField<uint32_t>(VT_FULL_VERTEX_COUNT, 0);
  }
  uint32_t culling_vertex_count() const {
    return GetField<uint32_t>(VT_CULLING_VERTEX_COUNT, 0);
  }
  uint32_t cube_count() const {
    return GetField<uint32_t>(VT_CUBE_COUNT, 0);
  }
  const ::flatbuffers::Vector<const ysm::bake::fb::CubeGroupInfo *> *cube_group_info() const {
    return GetPointer<const ::flatbuffers::Vector<const ysm::bake::fb::CubeGroupInfo *> *>(VT_CUBE_GROUP_INFO);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CUBE_INDICES) &&
           verifier.VerifyVector(cube_indices()) &&
           VerifyField<uint32_t>(verifier, VT_FULL_VERTEX_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_CULLING_VERTEX_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_CUBE_COUNT, 4) &&
           VerifyOffset(verifier, VT_CUBE_GROUP_INFO) &&
           verifier.VerifyVector(cube_group_info()) &&
           verifier.EndTable();
  }
};

struct BonePartitionInfoBuilder {
  typedef BonePartitionInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cube_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> cube_indices) {
    fbb_.AddOffset(BonePartitionInfo::VT_CUBE_INDICES, cube_indices);
  }
  void add_full_vertex_count(uint32_t full_vertex_count) {
    fbb_.AddElement<uint32_t>(BonePartitionInfo::VT_FULL_VERTEX_COUNT, full_vertex_count, 0);
  }
  void add_culling_vertex_count(uint32_t culling_vertex_count) {
    fbb_.AddElement<uint32_t>(BonePartitionInfo::VT_CULLING_VERTEX_COUNT, culling_vertex_count, 0);
  }
  void add_cube_count(uint32_t cube_count) {
    fbb_.AddElement<uint32_t>(BonePartitionInfo::VT_CUBE_COUNT, cube_count, 0);
  }
  void add_cube_group_info(::flatbuffers::Offset<::flatbuffers::Vector<const ysm::bake::fb::CubeGroupInfo *>> cube_group_info) {
    fbb_.AddOffset(BonePartitionInfo::VT_CUBE_GROUP_INFO, cube_group_info);
  }
  explicit BonePartitionInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BonePartitionInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BonePartitionInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BonePartitionInfo> CreateBonePartitionInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> cube_indices = 0,
    uint32_t full_vertex_count = 0,
    uint32_t culling_vertex_count = 0,
    uint32_t cube_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ysm::bake::fb::CubeGroupInfo *>> cube_group_info = 0) {
  BonePartitionInfoBuilder builder_(_fbb);
  builder_.add_cube_group_info(cube_group_info);
  builder_.add_cube_count(cube_count);
  builder_.add_culling_vertex_count(culling_vertex_count);
  builder_.add_full_vertex_count(full_vertex_count);
  builder_.add_cube_indices(cube_indices);
  return builder_.Finish();
}

struct BonePartitionInfo::Traits {
  using type = BonePartitionInfo;
  static auto constexpr Create = CreateBonePartitionInfo;
};

inline ::flatbuffers::Offset<BonePartitionInfo> CreateBonePartitionInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *cube_indices = nullptr,
    uint32_t full_vertex_count = 0,
    uint32_t culling_vertex_count = 0,
    uint32_t cube_count = 0,
    const std::vector<ysm::bake::fb::CubeGroupInfo> *cube_group_info = nullptr) {
  auto cube_indices__ = cube_indices ? _fbb.CreateVector<uint32_t>(*cube_indices) : 0;
  auto cube_group_info__ = cube_group_info ? _fbb.CreateVectorOfStructs<ysm::bake::fb::CubeGroupInfo>(*cube_group_info) : 0;
  return ysm::bake::fb::CreateBonePartitionInfo(
      _fbb,
      cube_indices__,
      full_vertex_count,
      culling_vertex_count,
      cube_count,
      cube_group_info__);
}

struct BoneInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoneInfoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CUTOUT = 4,
    VT_CUTOUT_NO_CULLING = 6,
    VT_TRANSLUCENT = 8,
    VT_TRANSLUCENT_CULLING = 10,
    VT_SOLID = 12,
    VT_PIVOT = 14,
    VT_PARENT_INDEX = 16,
    VT_SUBTREE_END = 18,
    VT_DEPTH = 20
  };
  const ysm::bake::fb::BonePartitionInfo *cutout() const {
    return GetPointer<const ysm::bake::fb::BonePartitionInfo *>(VT_CUTOUT);
  }
  const ysm::bake::fb::BonePartitionInfo *cutout_no_culling() const {
    return GetPointer<const ysm::bake::fb::BonePartitionInfo *>(VT_CUTOUT_NO_CULLING);
  }
  const ysm::bake::fb::BonePartitionInfo *translucent() const {
    return GetPointer<const ysm::bake::fb::BonePartitionInfo *>(VT_TRANSLUCENT);
  }
  const ysm::bake::fb::BonePartitionInfo *translucent_culling() const {
    return GetPointer<const ysm::bake::fb::BonePartitionInfo *>(VT_TRANSLUCENT_CULLING);
  }
  bool solid() const {
    return GetField<uint8_t>(VT_SOLID, 0) != 0;
  }
  const ::flatbuffers::Vector<float> *pivot() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_PIVOT);
  }
  uint32_t parent_index() const {
    return GetField<uint32_t>(VT_PARENT_INDEX, 4294967295);
  }
  uint32_t subtree_end() const {
    return GetField<uint32_t>(VT_SUBTREE_END, 0);
  }
  uint32_t depth() const {
    return GetField<uint32_t>(VT_DEPTH, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CUTOUT) &&
           verifier.VerifyTable(cutout()) &&
           VerifyOffset(verifier, VT_CUTOUT_NO_CULLING) &&
           verifier.VerifyTable(cutout_no_culling()) &&
           VerifyOffset(verifier, VT_TRANSLUCENT) &&
           verifier.VerifyTable(translucent()) &&
           VerifyOffset(verifier, VT_TRANSLUCENT_CULLING) &&
           verifier.VerifyTable(translucent_culling()) &&
           VerifyField<uint8_t>(verifier, VT_SOLID, 1) &&
           VerifyOffset(verifier, VT_PIVOT) &&
           verifier.VerifyVector(pivot()) &&
           VerifyField<uint32_t>(verifier, VT_PARENT_INDEX, 4) &&
           VerifyField<uint32_t>(verifier, VT_SUBTREE_END, 4) &&
           VerifyField<uint32_t>(verifier, VT_DEPTH, 4) &&
           verifier.EndTable();
  }
};

struct BoneInfoBuilder {
  typedef BoneInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cutout(::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> cutout) {
    fbb_.AddOffset(BoneInfo::VT_CUTOUT, cutout);
  }
  void add_cutout_no_culling(::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> cutout_no_culling) {
    fbb_.AddOffset(BoneInfo::VT_CUTOUT_NO_CULLING, cutout_no_culling);
  }
  void add_translucent(::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> translucent) {
    fbb_.AddOffset(BoneInfo::VT_TRANSLUCENT, translucent);
  }
  void add_translucent_culling(::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> translucent_culling) {
    fbb_.AddOffset(BoneInfo::VT_TRANSLUCENT_CULLING, translucent_culling);
  }
  void add_solid(bool solid) {
    fbb_.AddElement<uint8_t>(BoneInfo::VT_SOLID, static_cast<uint8_t>(solid), 0);
  }
  void add_pivot(::flatbuffers::Offset<::flatbuffers::Vector<float>> pivot) {
    fbb_.AddOffset(BoneInfo::VT_PIVOT, pivot);
  }
  void add_parent_index(uint32_t parent_index) {
    fbb_.AddElement<uint32_t>(BoneInfo::VT_PARENT_INDEX, parent_index, 4294967295);
  }
  void add_subtree_end(uint32_t subtree_end) {
    fbb_.AddElement<uint32_t>(BoneInfo::VT_SUBTREE_END, subtree_end, 0);
  }
  void add_depth(uint32_t depth) {
    fbb_.AddElement<uint32_t>(BoneInfo::VT_DEPTH, depth, 0);
  }
  explicit BoneInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoneInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoneInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoneInfo> CreateBoneInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> cutout = 0,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> cutout_no_culling = 0,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> translucent = 0,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> translucent_culling = 0,
    bool solid = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> pivot = 0,
    uint32_t parent_index = 4294967295,
    uint32_t subtree_end = 0,
    uint32_t depth = 0) {
  BoneInfoBuilder builder_(_fbb);
  builder_.add_depth(depth);
  builder_.add_subtree_end(subtree_end);
  builder_.add_parent_index(parent_index);
  builder_.add_pivot(pivot);
  builder_.add_translucent_culling(translucent_culling);
  builder_.add_translucent(translucent);
  builder_.add_cutout_no_culling(cutout_no_culling);
  builder_.add_cutout(cutout);
  builder_.add_solid(solid);
  return builder_.Finish();
}

struct BoneInfo::Traits {
  using type = BoneInfo;
  static auto constexpr Create = CreateBoneInfo;
};

inline ::flatbuffers::Offset<BoneInfo> CreateBoneInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> cutout = 0,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> cutout_no_culling = 0,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> translucent = 0,
    ::flatbuffers::Offset<ysm::bake::fb::BonePartitionInfo> translucent_culling = 0,
    bool solid = false,
    const std::vector<float> *pivot = nullptr,
    uint32_t parent_index = 4294967295,
    uint32_t subtree_end = 0,
    uint32_t depth = 0) {
  auto pivot__ = pivot ? _fbb.CreateVector<float>(*pivot) : 0;
  return ysm::bake::fb::CreateBoneInfo(
      _fbb,
      cutout,
      cutout_no_culling,
      translucent,
      translucent_culling,
      solid,
      pivot__,
      parent_index,
      subtree_end,
      depth);
}

struct CubeData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CubeDataBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CUTOUT = 4,
    VT_CUTOUT_NO_CULLING = 6,
    VT_TRANSLUCENT = 8,
    VT_TRANSLUCENT_CULLING = 10
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *cutout() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *>(VT_CUTOUT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *cutout_no_culling() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *>(VT_CUTOUT_NO_CULLING);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *translucent() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *>(VT_TRANSLUCENT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *translucent_culling() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *>(VT_TRANSLUCENT_CULLING);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CUTOUT) &&
           verifier.VerifyVector(cutout()) &&
           verifier.VerifyVectorOfTables(cutout()) &&
           VerifyOffset(verifier, VT_CUTOUT_NO_CULLING) &&
           verifier.VerifyVector(cutout_no_culling()) &&
           verifier.VerifyVectorOfTables(cutout_no_culling()) &&
           VerifyOffset(verifier, VT_TRANSLUCENT) &&
           verifier.VerifyVector(translucent()) &&
           verifier.VerifyVectorOfTables(translucent()) &&
           VerifyOffset(verifier, VT_TRANSLUCENT_CULLING) &&
           verifier.VerifyVector(translucent_culling()) &&
           verifier.VerifyVectorOfTables(translucent_culling()) &&
           verifier.EndTable();
  }
};

struct CubeDataBuilder {
  typedef CubeData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cutout(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> cutout) {
    fbb_.AddOffset(CubeData::VT_CUTOUT, cutout);
  }
  void add_cutout_no_culling(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> cutout_no_culling) {
    fbb_.AddOffset(CubeData::VT_CUTOUT_NO_CULLING, cutout_no_culling);
  }
  void add_translucent(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> translucent) {
    fbb_.AddOffset(CubeData::VT_TRANSLUCENT, translucent);
  }
  void add_translucent_culling(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> translucent_culling) {
    fbb_.AddOffset(CubeData::VT_TRANSLUCENT_CULLING, translucent_culling);
  }
  explicit CubeDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CubeData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CubeData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CubeData> CreateCubeData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> cutout = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> cutout_no_culling = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> translucent = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>> translucent_culling = 0) {
  CubeDataBuilder builder_(_fbb);
  builder_.add_translucent_culling(translucent_culling);
  builder_.add_translucent(translucent);
  builder_.add_cutout_no_culling(cutout_no_culling);
  builder_.add_cutout(cutout);
  return builder_.Finish();
}

struct CubeData::Traits {
  using type = CubeData;
  static auto constexpr Create = CreateCubeData;
};

inline ::flatbuffers::Offset<CubeData> CreateCubeDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *cutout = nullptr,
    const std::vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *cutout_no_culling = nullptr,
    const std::vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *translucent = nullptr,
    const std::vector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>> *translucent_culling = nullptr) {
  auto cutout__ = cutout ? _fbb.CreateVector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>(*cutout) : 0;
  auto cutout_no_culling__ = cutout_no_culling ? _fbb.CreateVector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>(*cutout_no_culling) : 0;
  auto translucent__ = translucent ? _fbb.CreateVector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>(*translucent) : 0;
  auto translucent_culling__ = translucent_culling ? _fbb.CreateVector<::flatbuffers::Offset<ysm::bake::fb::CubeGroup>>(*translucent_culling) : 0;
  return ysm::bake::fb::CreateCubeData(
      _fbb,
      cutout__,
      cutout_no_culling__,
      translucent__,
      translucent_culling__);
}

struct BakedModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BakedModelBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BONES = 4,
    VT_SORTED_BONE_INDICES = 6,
    VT_CUBES = 8,
    VT_GUI_NO_SHADOW = 10,
    VT_HAS_PBR = 12
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::BoneInfo>> *bones() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::BoneInfo>> *>(VT_BONES);
  }
  const ::flatbuffers::Vector<uint16_t> *sorted_bone_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint16_t> *>(VT_SORTED_BONE_INDICES);
  }
  const ysm::bake::fb::CubeData *cubes() const {
    return GetPointer<const ysm::bake::fb::CubeData *>(VT_CUBES);
  }
  bool gui_no_shadow() const {
    return GetField<uint8_t>(VT_GUI_NO_SHADOW, 0) != 0;
  }
  bool has_pbr() const {
    return GetField<uint8_t>(VT_HAS_PBR, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BONES) &&
           verifier.VerifyVector(bones()) &&
           verifier.VerifyVectorOfTables(bones()) &&
           VerifyOffset(verifier, VT_SORTED_BONE_INDICES) &&
           verifier.VerifyVector(sorted_bone_indices()) &&
           VerifyOffset(verifier, VT_CUBES) &&
           verifier.VerifyTable(cubes()) &&
           VerifyField<uint8_t>(verifier, VT_GUI_NO_SHADOW, 1) &&
           VerifyField<uint8_t>(verifier, VT_HAS_PBR, 1) &&
           verifier.EndTable();
  }
};

struct BakedModelBuilder {
  typedef BakedModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bones(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::BoneInfo>>> bones) {
    fbb_.AddOffset(BakedModel::VT_BONES, bones);
  }
  void add_sorted_bone_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> sorted_bone_indices) {
    fbb_.AddOffset(BakedModel::VT_SORTED_BONE_INDICES, sorted_bone_indices);
  }
  void add_cubes(::flatbuffers::Offset<ysm::bake::fb::CubeData> cubes) {
    fbb_.AddOffset(BakedModel::VT_CUBES, cubes);
  }
  void add_gui_no_shadow(bool gui_no_shadow) {
    fbb_.AddElement<uint8_t>(BakedModel::VT_GUI_NO_SHADOW, static_cast<uint8_t>(gui_no_shadow), 0);
  }
  void add_has_pbr(bool has_pbr) {
    fbb_.AddElement<uint8_t>(BakedModel::VT_HAS_PBR, static_cast<uint8_t>(has_pbr), 0);
  }
  explicit BakedModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BakedModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BakedModel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BakedModel> CreateBakedModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ysm::bake::fb::BoneInfo>>> bones = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint16_t>> sorted_bone_indices = 0,
    ::flatbuffers::Offset<ysm::bake::fb::CubeData> cubes = 0,
    bool gui_no_shadow = false,
    bool has_pbr = false) {
  BakedModelBuilder builder_(_fbb);
  builder_.add_cubes(cubes);
  builder_.add_sorted_bone_indices(sorted_bone_indices);
  builder_.add_bones(bones);
  builder_.add_has_pbr(has_pbr);
  builder_.add_gui_no_shadow(gui_no_shadow);
  return builder_.Finish();
}

struct BakedModel::Traits {
  using type = BakedModel;
  static auto constexpr Create = CreateBakedModel;
};

inline ::flatbuffers::Offset<BakedModel> CreateBakedModelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ysm::bake::fb::BoneInfo>> *bones = nullptr,
    const std::vector<uint16_t> *sorted_bone_indices = nullptr,
    ::flatbuffers::Offset<ysm::bake::fb::CubeData> cubes = 0,
    bool gui_no_shadow = false,
    bool has_pbr = false) {
  auto bones__ = bones ? _fbb.CreateVector<::flatbuffers::Offset<ysm::bake::fb::BoneInfo>>(*bones) : 0;
  auto sorted_bone_indices__ = sorted_bone_indices ? _fbb.CreateVector<uint16_t>(*sorted_bone_indices) : 0;
  return ysm::bake::fb::CreateBakedModel(
      _fbb,
      bones__,
      sorted_bone_indices__,
      cubes,
      gui_no_shadow,
      has_pbr);
}

inline const ysm::bake::fb::BakedModel *GetBakedModel(const void *buf) {
  return ::flatbuffers::GetRoot<ysm::bake::fb::BakedModel>(buf);
}

inline const ysm::bake::fb::BakedModel *GetSizePrefixedBakedModel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ysm::bake::fb::BakedModel>(buf);
}

template <bool B = false>
inline bool VerifyBakedModelBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ysm::bake::fb::BakedModel>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedBakedModelBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ysm::bake::fb::BakedModel>(nullptr);
}

inline void FinishBakedModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ysm::bake::fb::BakedModel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBakedModelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ysm::bake::fb::BakedModel> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fb
}  // namespace bake
}  // namespace ysm

#endif  // FLATBUFFERS_GENERATED_BAKEDMODEL_YSM_BAKE_FB_H_
